/**
 * Supabase Database Types
 *
 * This file will be auto-generated by running:
 * npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts
 *
 * For now, we use the types from ./index.ts
 * After Supabase project is set up, replace this file with generated types.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Placeholder — will be replaced by auto-generated types
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: string;
          full_name: string;
          email: string;
          phone: string | null;
          avatar_url: string | null;
          is_verified: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          role: string;
          full_name: string;
          email: string;
          phone?: string | null;
          avatar_url?: string | null;
          is_verified?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: string;
          full_name?: string;
          email?: string;
          phone?: string | null;
          avatar_url?: string | null;
          is_verified?: boolean;
          is_active?: boolean;
          updated_at?: string;
        };
      };
      talents: {
        Row: {
          id: string;
          profile_id: string;
          category: string;
          gender: string | null;
          date_of_birth: string | null;
          height_cm: number | null;
          weight_kg: number | null;
          city: string | null;
          province: string | null;
          address: string | null;
          bio: string | null;
          ktp_number: string | null;
          ktp_photo_url: string | null;
          selfie_photo_url: string | null;
          verification_status: string;
          rating_avg: number;
          rating_count: number;
          total_jobs_completed: number;
          wallet_balance: number;
          daily_rate: number | null;
          is_available: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          category: string;
          gender?: string | null;
          date_of_birth?: string | null;
          height_cm?: number | null;
          weight_kg?: number | null;
          city?: string | null;
          province?: string | null;
          address?: string | null;
          bio?: string | null;
          daily_rate?: number | null;
          is_available?: boolean;
        };
        Update: Partial<Database["public"]["Tables"]["talents"]["Insert"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
